### ISSUE TITLE
AUTO_INCREMENT

### ISSUE THREAD

**Issue by Zerstoren** [waitaction/websql-orm#1]
Hello. What about create table with AUTO_INCREMENT when primary key is number?

In tests and examples I found only string primary key, but in code i see no included auto increment option. This is common relational db feature.

As example, this code can't be runned successful: 

// Generated by websql-orm
CREATE TABLE IF NOT EXISTS `surveys` (`id` NUMERIC PRIMARY KEY NOT NULL, `title` TEXT)
// And this query generated by websq-orm too.
insert into `surveys`  (`id`,`title`) values (?, ?)
[null, "example"]

Browser return error "could not execute statement due to a constraint failure (19 NOT NULL constraint failed: surveys.id)", becouse create table need to look like this:
CREATE TABLE IF NOT EXISTS `surveys` (`id` NUMERIC PRIMARY KEY AUTO_INCREMENT, `title` TEXT)

**Comment by waitaction** [comment]
SQLite uses rowid as the default auto-increment ID

**Comment by waitaction** [comment]
now , you can also use `ColumnType.NUMBER | ColumnType.PRIMARY`
